import java.io.IOException; 
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.annotation.WebServlet;

@WebServlet("/servlet/generateHtml")
public class Dynamic_Servlet extends HttpServlet {
    static final long serialVersionUID = 1L;

    // Handles GET requests to display the form
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        
        out.println("<html>");
        out.println("<head><title>Dynamic HTML Output</title></head>");
        out.println("<body>");
        out.println("<h1>Welcome to the Dynamic HTML Page!</h1>");
        out.println("<p>This page is generated by a servlet.</p>");
        out.println("<p>Current Time: " + new java.util.Date() + "</p>");
        out.println("<form action='generateHtml' method='post'>");  
        out.println("Name: <input type='text' name='name'><br>");
        out.println("Age: <input type='text' name='age'><br>");
        out.println("<input type='submit' value='Submit'>");
        out.println("</form>");
        out.println("</body>");
        out.println("</html>");
    }

    // Handles POST requests to process the form submission
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        String name = request.getParameter("name");
        String age = request.getParameter("age");

        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        out.println("<html>");
        out.println("<head><title>Form Processed</title></head>");
        out.println("<body>");
        out.println("<h1>Form Processed Successfully!</h1>");
        out.println("<p>Name: " + name + "</p>");
        out.println("<p>Age: " + age + "</p>");
        out.println("</body>");
        out.println("</html>");
    }
}
