import java.io.IOException; 
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.annotation.WebServlet;

@WebServlet("/servlet/generateHtml")
public class Time_Servlet extends HttpServlet {
    static final long serialVersionUID = 1L;

    // Handles GET requests to display the current time
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        
        out.println("<html>");
        out.println("<head><title>Dynamic HTML Output</title></head>");
        out.println("<body>");
        out.println("<h1>Welcome to the Dynamic HTML Page!</h1>");
        out.println("<p>This page is generated by a servlet.</p>");
        out.println("<p>Current Time: " + new java.util.Date() + "</p>");
        out.println("</body>");
        out.println("</html>");
    }
}
